(function(){
const TOOL_KEY='cncCopilotTools',PROJECT_KEY='cncCopilotProjects',PROFILE_KEY='cncCopilotProfile';
const seedTools=[
  {id:'wnmg080408ha',type:'insert',name:'WNMG 080408 HA',code:'PC9030 · Korloy',iso:'M',role:'Черновая / получистовая',details:'R0,8 · нержавейка и сталь',favorite:true,builtin:true},
  {id:'cnmg120404',type:'insert',name:'CNMG 120404',code:'R0,4',iso:'P/M',role:'Чистовая / универсальная',details:'Точение наружного диаметра и торца',favorite:true,builtin:true},
  {id:'mwlrr2525m08',type:'holder',name:'MWLNR 2525M08',code:'Наружная державка',iso:'P/M',role:'Под пластину WNMG 08',details:'Сечение 25×25 мм · правое исполнение',favorite:false,builtin:true},
  {id:'boring25',type:'holder',name:'Расточная державка Ø25',code:'Внутренняя обработка',iso:'P/M',role:'Расточка отверстий',details:'Контролировать вылет и риск вибрации',favorite:false,builtin:true},
  {id:'bmt40er25',type:'holder',name:'BMT40–ER25',code:'Приводной блок',iso:'P/M/N',role:'Сверление и фрезерование',details:'Для револьвера CK52PT-Y',favorite:false,builtin:true},
  {id:'drill4',type:'drill',name:'Сверло Ø4',code:'Спиральное',iso:'P/M',role:'Осевое сверление',details:'Угол вершины 118–135°',favorite:false,builtin:true}
];
const defaults={name:'Єрошов Іван',machine:'Tengyue CK52PT-Y',control:'SINUMERIK 828D / ShopTurn',turret:'15',units:'metric',theme:'system'};
let root=null,ctx={},state={toolFilter:'all',toolQuery:'',showToolForm:false,projectQuery:''};
const safeParse=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}};
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[ch]);
const typeName={insert:'Пластина',holder:'Державка',drill:'Сверло',other:'Оснастка'};
function tools(){const saved=safeParse(TOOL_KEY,[]);const ids=new Set(saved.map(x=>x.id));return [...saved,...seedTools.filter(x=>!ids.has(x.id))]}
function saveTools(items){localStorage.setItem(TOOL_KEY,JSON.stringify(items));dispatchEvent(new CustomEvent('cnc-data-changed'))}
function projects(){return safeParse(PROJECT_KEY,[])}
function saveProjects(items){localStorage.setItem(PROJECT_KEY,JSON.stringify(items));dispatchEvent(new CustomEvent('cnc-data-changed'))}
function profile(){return {...defaults,...safeParse(PROFILE_KEY,{})}}
function saveProfile(value){localStorage.setItem(PROFILE_KEY,JSON.stringify(value));dispatchEvent(new CustomEvent('cnc-data-changed'))}
function moduleIcon(name,size=26){return ctx.icon?ctx.icon(name,size):''}
function empty(title,text){return `<div class="module-empty glass"><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`}
function instrument(){
  const all=tools();
  const list=all.filter(x=>state.toolFilter==='all'||state.toolFilter==='favorite'&&x.favorite||x.type===state.toolFilter);
  return `<section class="workspace-module"><div class="module-toolbar"><label class="module-search glass">${moduleIcon('search',20)}<input id="tool-search" value="${esc(state.toolQuery)}" placeholder="Маркировка или назначение" aria-label="Поиск инструмента"></label><button class="module-add" id="tool-add" aria-label="Добавить инструмент">+</button></div><div class="module-tabs"><button class="${state.toolFilter==='all'?'active':''}" data-tool-filter="all">Все</button><button class="${state.toolFilter==='insert'?'active':''}" data-tool-filter="insert">Пластины</button><button class="${state.toolFilter==='holder'?'active':''}" data-tool-filter="holder">Державки</button><button class="${state.toolFilter==='drill'?'active':''}" data-tool-filter="drill">Сверла</button><button class="${state.toolFilter==='favorite'?'active':''}" data-tool-filter="favorite">Избранное</button></div><div class="module-summary"><div class="summary-card glass"><small>Всего</small><strong>${all.length}</strong></div><div class="summary-card glass"><small>Пластин</small><strong>${all.filter(x=>x.type==='insert').length}</strong></div><div class="summary-card glass"><small>Избранных</small><strong>${all.filter(x=>x.favorite).length}</strong></div></div>${state.showToolForm?toolForm():''}<div class="module-list">${list.length?list.map(toolCard).join(''):empty('Инструментов пока нет','Добавь свой инструмент кнопкой «+».')}<div id="tool-no-results" hidden>${empty('Ничего не найдено','Измени запрос или добавь свой инструмент.')}</div></div></section>`;
}
function toolCard(x){const custom=!x.builtin,search=esc(`${x.name} ${x.code} ${x.iso} ${x.role} ${x.details}`.toLocaleLowerCase('ru'));return `<article class="module-card" data-tool-card data-search="${search}"><div class="module-card-head"><span class="module-card-icon">${moduleIcon(x.type==='insert'?'tool':x.type==='drill'?'offset':'turret',25)}</span><div class="module-card-title"><small>${typeName[x.type]||typeName.other}</small><h2>${esc(x.name)}</h2></div></div><p><strong>${esc(x.code)}</strong><br>${esc(x.details)}</p><div class="tool-tags"><span class="tool-tag iso-${String(x.iso).toLowerCase()}">ISO ${esc(x.iso)}</span><span class="tool-tag">${esc(x.role)}</span></div><div class="tool-actions"><button class="favorite ${x.favorite?'active':''}" data-tool-favorite="${esc(x.id)}" aria-label="Избранное">☆</button><button class="wide" data-tool-copy="${esc(x.id)}">Копировать</button>${custom?`<button class="danger" data-tool-delete="${esc(x.id)}">Удалить</button>`:''}</div></article>`}
function toolForm(){return `<form id="tool-form" class="module-form glass"><h2>Добавить в мой инструмент</h2><div class="form-grid"><div class="form-field"><label>Тип</label><select name="type"><option value="insert">Пластина</option><option value="holder">Державка</option><option value="drill">Сверло</option><option value="other">Оснастка</option></select></div><div class="form-field"><label>ISO-группа</label><select name="iso"><option>P</option><option>M</option><option>K</option><option>N</option><option>S</option><option>H</option><option>P/M</option></select></div><div class="form-field full"><label>Маркировка</label><input name="name" required placeholder="Например CNMG 120404"></div><div class="form-field"><label>Сплав / код</label><input name="code" placeholder="PC9030, R0,4…"></div><div class="form-field"><label>Назначение</label><input name="role" placeholder="Черновая, чистовая…"></div><div class="form-field full"><label>Примечание</label><input name="details" placeholder="Материал, операция, особенности"></div></div><div class="form-actions"><button type="button" class="secondary-action" id="tool-cancel">Отмена</button><button class="primary-action">Сохранить</button></div></form>`}
function projectModule(){const all=projects();return `<section class="workspace-module"><div class="module-toolbar"><label class="module-search glass">${moduleIcon('search',20)}<input id="project-search" value="${esc(state.projectQuery)}" placeholder="Поиск по сохранённым расчётам" aria-label="Поиск проектов"></label></div><div class="module-summary"><div class="summary-card glass"><small>Сохранено</small><strong>${all.length}</strong></div><div class="summary-card glass"><small>Расчётов</small><strong>${all.filter(x=>x.type).length}</strong></div><div class="summary-card glass"><small>На iPhone</small><strong>100%</strong></div></div><div class="project-toolbar"><button id="export-projects" class="secondary-action">Экспорт JSON</button><button id="clear-projects" class="danger-action" ${all.length?'':'disabled'}>Очистить</button></div><div class="module-list">${all.length?all.map(projectCard).join(''):empty('Проектов пока нет','В расчёте нажми «Сохранить» — результат появится здесь.')}<div id="project-no-results" hidden>${empty('Совпадений нет','Попробуй изменить запрос.')}</div></div></section>`}
function projectCard(x,i){const date=x.savedAt?new Date(x.savedAt).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}):'Локально',search=esc(`${x.type} ${x.title} ${x.details}`.toLocaleLowerCase('ru'));return `<article class="module-card project-card" data-project-card data-search="${search}"><div class="project-meta"><span class="project-type">${esc(x.type||'Расчёт')}</span><span>${esc(date)}</span></div><h2>${esc(x.title||'Без названия')}</h2><p>${esc(x.details||'Сохранённый результат')}</p><div class="project-actions"><button data-project-copy="${i}">Копировать</button><button data-project-delete="${i}" class="delete" aria-label="Удалить">×</button></div></article>`}
function profileModule(){const p=profile(),ts=tools().length,ps=projects().length;return `<section class="workspace-module"><article class="profile-hero glass"><div class="profile-avatar">${moduleIcon('user',32)}</div><div><h2>${esc(p.name)}</h2><p>Оператор · ${esc(p.machine)}</p></div></article><div class="profile-stats"><div class="profile-stat glass"><strong>${ts}</strong><small>Инструментов</small></div><div class="profile-stat glass"><strong>${ps}</strong><small>Проектов</small></div><div class="profile-stat glass"><strong>15</strong><small>Позиций</small></div></div><form id="profile-form" class="profile-panel glass"><h3>Станок и интерфейс</h3><label class="profile-row"><span>Имя оператора<small>Показывается только на этом устройстве</small></span><input name="name" value="${esc(p.name)}"></label><label class="profile-row"><span>Станок<small>Основной профиль оборудования</small></span><input name="machine" value="${esc(p.machine)}"></label><label class="profile-row"><span>Стойка<small>Система управления</small></span><input name="control" value="${esc(p.control)}"></label><label class="profile-row"><span>Позиций револьвера</span><input name="turret" inputmode="numeric" value="${esc(p.turret)}"></label><label class="profile-row"><span>Единицы</span><select name="units"><option value="metric" ${p.units==='metric'?'selected':''}>Метрические, мм</option><option value="inch" ${p.units==='inch'?'selected':''}>Дюймовые</option></select></label><label class="profile-row"><span>Тема</span><select name="theme"><option value="system" ${p.theme==='system'?'selected':''}>Как на iPhone</option><option value="dark" ${p.theme==='dark'?'selected':''}>Тёмная</option><option value="light" ${p.theme==='light'?'selected':''}>Светлая</option></select></label><button class="primary-action" style="width:100%;margin-top:13px">Сохранить профиль</button></form><div class="profile-panel glass"><h3>Локальные данные</h3><div class="profile-actions"><button id="backup-all" class="secondary-action">Резервная копия</button><button id="import-open" class="secondary-action">Восстановить</button><input id="import-file" type="file" accept="application/json" hidden><button id="reset-data" class="danger-action">Сбросить мои данные</button></div></div></section>`}
function download(filename,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function applyTheme(value){const light=value==='light'||value==='system'&&matchMedia('(prefers-color-scheme: light)').matches;document.body.classList.toggle('light',light);document.querySelector('#calculations-root')?.classList.toggle('light',light);document.documentElement.dataset.theme=value}
function applyLiveSearch(cardSelector,emptySelector,value){const query=value.trim().toLocaleLowerCase('ru'),cards=[...root.querySelectorAll(cardSelector)];let visible=0;cards.forEach(card=>{const show=!query||card.dataset.search.includes(query);card.hidden=!show;if(show)visible++});const emptyState=root.querySelector(emptySelector);if(emptyState)emptyState.hidden=!cards.length||visible>0}
function bindInstrument(){
  const search=root.querySelector('#tool-search');search?.addEventListener('input',e=>{state.toolQuery=e.target.value;applyLiveSearch('[data-tool-card]','#tool-no-results',state.toolQuery)});applyLiveSearch('[data-tool-card]','#tool-no-results',state.toolQuery);
  root.querySelector('#tool-add')?.addEventListener('click',()=>{state.showToolForm=!state.showToolForm;render('instrument');setTimeout(()=>root.querySelector('#tool-form')?.scrollIntoView({behavior:'smooth',block:'start'}),20)});
  root.querySelectorAll('[data-tool-filter]').forEach(b=>b.onclick=()=>{state.toolFilter=b.dataset.toolFilter;render('instrument')});
  root.querySelector('#tool-cancel')?.addEventListener('click',()=>{state.showToolForm=false;render('instrument')});
  root.querySelector('#tool-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),item={id:`custom-${Date.now()}`,type:f.get('type'),name:String(f.get('name')).trim(),code:String(f.get('code')).trim()||'Мой инструмент',iso:f.get('iso'),role:String(f.get('role')).trim()||'Не указано',details:String(f.get('details')).trim()||'Добавлено вручную',favorite:true,builtin:false};if(!item.name)return;const custom=safeParse(TOOL_KEY,[]);custom.unshift(item);saveTools(custom);state.showToolForm=false;ctx.toast('Инструмент сохранён');ctx.viewport?.reset(0);render('instrument')});
  root.querySelectorAll('[data-tool-favorite]').forEach(b=>b.onclick=()=>{const id=b.dataset.toolFavorite,all=tools(),item=all.find(x=>x.id===id),custom=safeParse(TOOL_KEY,[]).filter(x=>x.id!==id);if(!item)return;custom.unshift({...item,favorite:!item.favorite,builtin:item.builtin});saveTools(custom);render('instrument')});
  root.querySelectorAll('[data-tool-copy]').forEach(b=>b.onclick=async()=>{const x=tools().find(t=>t.id===b.dataset.toolCopy);await navigator.clipboard?.writeText(`${x.name} · ${x.code} · ISO ${x.iso} · ${x.role}`);ctx.toast('Инструмент скопирован')});
  root.querySelectorAll('[data-tool-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Удалить этот инструмент?'))return;saveTools(safeParse(TOOL_KEY,[]).filter(x=>x.id!==b.dataset.toolDelete));render('instrument')});
}
function bindProjects(){const search=root.querySelector('#project-search');search?.addEventListener('input',e=>{state.projectQuery=e.target.value;applyLiveSearch('[data-project-card]','#project-no-results',state.projectQuery)});applyLiveSearch('[data-project-card]','#project-no-results',state.projectQuery);root.querySelectorAll('[data-project-copy]').forEach(b=>b.onclick=async()=>{const x=projects()[Number(b.dataset.projectCopy)];await navigator.clipboard?.writeText(`${x.type}: ${x.title}\n${x.details}`);ctx.toast('Проект скопирован')});root.querySelectorAll('[data-project-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Удалить сохранённый расчёт?'))return;const x=projects();x.splice(Number(b.dataset.projectDelete),1);saveProjects(x);render('projects')});root.querySelector('#clear-projects')?.addEventListener('click',()=>{if(!confirm('Удалить все сохранённые расчёты?'))return;saveProjects([]);render('projects')});root.querySelector('#export-projects')?.addEventListener('click',()=>download('cnc-copilot-projects.json',{version:1,projects:projects()}))}
function bindProfile(){root.querySelector('#profile-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),p={name:String(f.get('name')).trim()||defaults.name,machine:String(f.get('machine')).trim()||defaults.machine,control:String(f.get('control')).trim()||defaults.control,turret:String(f.get('turret')).trim()||'15',units:f.get('units'),theme:f.get('theme')};saveProfile(p);applyTheme(p.theme);ctx.toast('Профиль сохранён');ctx.viewport?.reset(0);render('profile')});root.querySelector('#backup-all')?.addEventListener('click',()=>download('cnc-copilot-backup.json',{version:1,createdAt:new Date().toISOString(),profile:profile(),tools:safeParse(TOOL_KEY,[]),projects:projects(),favorites:safeParse('cnc-code-favorites',[])}));root.querySelector('#import-open')?.addEventListener('click',()=>root.querySelector('#import-file').click());root.querySelector('#import-file')?.addEventListener('change',async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.profile)saveProfile(data.profile);if(Array.isArray(data.tools))saveTools(data.tools);if(Array.isArray(data.projects))saveProjects(data.projects);if(Array.isArray(data.favorites))localStorage.setItem('cnc-code-favorites',JSON.stringify(data.favorites));applyTheme(profile().theme);ctx.toast('Данные восстановлены');render('profile')}catch{ctx.toast('Файл резервной копии повреждён')}});root.querySelector('#reset-data')?.addEventListener('click',()=>{if(!confirm('Удалить профиль, свой инструмент и проекты?'))return;[TOOL_KEY,PROJECT_KEY,PROFILE_KEY,'cnc-code-favorites'].forEach(k=>localStorage.removeItem(k));applyTheme('system');ctx.toast('Локальные данные сброшены');render('profile')})}
function render(name){if(!root)return;root.innerHTML=name==='instrument'?instrument():name==='projects'?projectModule():profileModule();if(name==='instrument')bindInstrument();else if(name==='projects')bindProjects();else bindProfile()}
window.CopilotModules={mount(name,target,options={}){root=target;ctx=options;render(name)},applyStoredTheme(){applyTheme(profile().theme)},setTheme(value){saveProfile({...profile(),theme:value});applyTheme(value)},counts(){return {tools:tools().length,projects:projects().length}}};
})();
