const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const app = $('#app');
const fmt = (n, d=3) => Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d,minimumFractionDigits:0});
const val = id => Number(String($(id)?.value || '').replace(',','.'));
const icon = (name) => ({
  identify:'<svg viewBox="0 0 32 32"><path d="M2 23 8 9l6 14 6-14 6 14h4"/><path d="m22 8 7 7M22 15l7-7"/></svg>',
  drill:'<svg viewBox="0 0 32 32"><path d="M15 2h5l-2 5 2 5-2 5 2 5-2 8"/><path d="M4 24h10m8 0h6M6 28h8m8 0h4"/></svg>',
  profile:'<svg viewBox="0 0 32 32"><path d="M2 24 8 8l6 16 6-16 6 16h4"/><path d="M2 27h28M8 5v3m12-3v3"/></svg>',
  favorite:'<svg viewBox="0 0 32 32"><path d="m16 3 4 8 9 1-6.5 6.3L24 27l-8-4.2L8 27l1.5-8.7L3 12l9-1z"/></svg>',
  reference:'<svg viewBox="0 0 32 32"><path d="M6 4h16a4 4 0 0 1 4 4v20H10a4 4 0 0 1-4-4z"/><path d="M10 22h16M11 9h10m-10 5h8"/></svg>',
  geometry:'<svg viewBox="0 0 32 32"><path d="m9 26 7-21 7 21zM4 26h24"/><path d="m24 4 5 3v6l-5 3-5-3V7z"/></svg>',
  fits:'<svg viewBox="0 0 32 32"><path d="M5 26V7m22 19V7M9 11h14M9 22h14"/><path d="m12 8-3 3 3 3m8-6 3 3-3 3m-8 5-3 3 3 3m8-6 3 3-3 3"/></svg>',
  roughness:'<svg viewBox="0 0 32 32"><path d="M2 22c4 0 4-12 8-12s4 12 8 12 4-12 8-12 4 12 4 12"/><path d="M2 27h28"/></svg>',
  position:'<svg viewBox="0 0 32 32"><circle cx="16" cy="16" r="10"/><circle cx="16" cy="16" r="3"/><path d="M16 2v8m0 12v8M2 16h8m12 0h8"/></svg>',
  deflection:'<svg viewBox="0 0 32 32"><path d="M4 5v22M4 10h20c3 0 4 2 4 5v7"/><path d="m24 19 4 4 4-4M8 6v8m4-8v8"/></svg>',
  weight:'<svg viewBox="0 0 32 32"><path d="M8 12h16l3 16H5z"/><path d="M11 12a5 5 0 1 1 10 0M16 7v5"/><text x="16" y="24" text-anchor="middle" fill="currentColor" stroke="none" font-size="7">kg</text></svg>',
  bolt:'<svg viewBox="0 0 32 32"><circle cx="16" cy="16" r="11"/><circle cx="16" cy="5" r="2"/><circle cx="27" cy="16" r="2"/><circle cx="16" cy="27" r="2"/><circle cx="5" cy="16" r="2"/><circle cx="16" cy="16" r="2"/></svg>',
  wires:'<svg viewBox="0 0 32 32"><path d="M3 25 9 9l6 16 6-16 8 16"/><circle cx="10" cy="15" r="3"/><circle cx="20" cy="15" r="3"/><circle cx="15" cy="24" r="3"/></svg>',
  drillpoint:'<svg viewBox="0 0 32 32"><path d="M12 3h8l-2 5 2 5-2 5 2 5-4 7-4-7 2-5-2-5 2-5z"/><path d="M6 23h20M16 23v7"/></svg>',
  time:'<svg viewBox="0 0 32 32"><circle cx="16" cy="17" r="12"/><path d="M16 5V2m-4 0h8M16 17l6-5M16 17l-4 4"/></svg>',
  wear:'<svg viewBox="0 0 32 32"><path d="m5 25 5-18 17 5-5 17z"/><path d="m10 7 8 11 9-6M15 24l4-6"/><circle cx="19" cy="18" r="2"/></svg>'
}[name]);

const tools = [
  ['identify','Определитель резьбы','Диаметр + шаг → ближайший стандарт'],
  ['drill','Сверло под резьбу','Режущий или формующий метчик'],
  ['profile','Профиль резьбы','Глубины и основные диаметры'],
  ['geometry','Геометрия','Конус, шестигранник, координаты']
];
const proTools = [
  ['fits','Допуски ISO 286','Пределы размера и зона допуска'],
  ['roughness','Шероховатость','Ra и Rz по подаче и радиусу'],
  ['position','Истинная позиция','Смещение отверстия и бонус MMC'],
  ['deflection','Прогиб расточной державки','Жёсткость, сила и риск вибрации']
];
const shopTools = [
  ['weight','Вес заготовки','Масса одной детали и всей партии'],
  ['bolt','Болтовая окружность','Координаты отверстий X/Y'],
  ['wires','Резьба по 3 проволочкам','Теоретический размер измерения'],
  ['drillpoint','Вершина сверла','Длина конуса и полная глубина'],
  ['time','Время обработки','Точение, сверление и отрезка'],
  ['wear','Износ пластины','Признаки, причины и действия']
];

const state = {route:'home', pitchMode:'mm', drillType:'cut', refGroup:'Все', geometry:'cone',weightShape:'round',timeType:'turn',wear:'flank'};
const titles = {identify:'Определитель резьбы',drill:'Сверло под резьбу',profile:'Профиль резьбы',favorites:'Избранное',reference:'Быстрый справочник',geometry:'Геометрия',fits:'Допуски ISO 286',roughness:'Шероховатость',position:'Истинная позиция',deflection:'Прогиб державки',weight:'Вес заготовки',bolt:'Болтовая окружность',wires:'Резьба по 3 проволочкам',drillpoint:'Вершина сверла',time:'Время обработки',wear:'Износ пластины',settings:'Настройки'};
const favorites = () => JSON.parse(localStorage.getItem('cncCopilotProjects') || '[]');
const saveFavorites = items => localStorage.setItem('cncCopilotProjects',JSON.stringify(items));
const toast = msg => {const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)};

function header(key, sub='Работает без интернета'){
  return `<header class="topbar"><button class="back" data-back aria-label="Назад">‹</button><div><p class="eyebrow">CNC COPILOT · РАСЧЁТЫ</p><h1 class="title">${titles[key]}</h1><p class="subtitle">${sub}</p></div></header>`;
}
function setRoute(route){state.route=route;render();scrollTo({top:0,behavior:'smooth'});const dockRoute=route==='favorites'?'favorites':route==='settings'?'settings':route==='reference'?'reference':'home';$$('.dock-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===dockRoute))}

function toolCards(list,start=0,compact=false){return list.map((t,i)=>`<button class="tool-card ${compact?'compact-card':''}" data-tool="${t[0]}"><span class="card-number">${String(start+i+1).padStart(2,'0')}</span><span class="tool-icon">${icon(t[0]==='favorites'?'favorite':t[0])}</span><h2>${t[1]}</h2><p>${t[2]}</p><span class="chev">›</span></button>`).join('')}
function home(){
  return `<nav class="calc-categories glass" aria-label="Категории расчётов"><button data-scroll="main-tools" class="active">Основные</button><button data-scroll="precision-tools">Точные</button><button data-scroll="shop-tools">Цеховые</button></nav><section id="main-tools"><div class="section-heading"><span>Основные</span></div><section class="tools-grid">${toolCards(tools)}</section></section><section id="precision-tools"><div class="section-heading pro-heading"><span>Точные расчёты</span></div><section class="pro-grid">${toolCards(proTools,4,true)}</section></section><section id="shop-tools"><div class="section-heading pro-heading"><span>Цеховые расчёты</span></div><section class="shop-grid">${toolCards(shopTools,8,true)}</section></section>`;
}

function identifyView(){return `${header('identify','Измерьте наружный диаметр и шаг')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Диаметр, мм</label><input id="idDiameter" class="input" inputmode="decimal" value="9,85"></div><div class="field"><label>${state.pitchMode==='mm'?'Шаг, мм':'Ниток на дюйм (TPI)'}</label><input id="idPitch" class="input" inputmode="decimal" value="${state.pitchMode==='mm'?'1,50':'20'}"></div><div class="field full"><label>Как измерен шаг</label><div class="segmented"><button data-pitch-mode="mm" class="${state.pitchMode==='mm'?'active':''}">мм</button><button data-pitch-mode="tpi" class="${state.pitchMode==='tpi'?'active':''}">TPI</button></div></div></div><button id="identifyBtn" class="primary" style="margin-top:14px">Определить</button></section><div id="identifyResult"></div>`}

function identifyCalc(){
  const d=val('#idDiameter'), raw=val('#idPitch'); if(!d||!raw){toast('Введите диаметр и шаг');return}
  const matches=EngineeringCore.identify(d,raw,state.pitchMode,THREAD_DATA);
  const root=$('#identifyResult'); if(!matches.length){root.innerHTML='<section class="panel glass empty"><div class="empty-icon">⌁</div>Совпадений не найдено. Проверьте измерения.</section>';return}
  const best=matches[0], drill=best.diameter-best.pitch;
  root.innerHTML=`<section class="result-card glass"><span class="result-label">Вероятное совпадение</span><div class="result-big">${best.label}</div><div class="result-lines"><div class="result-line"><span>Стандарт</span><strong>${best.standard}</strong></div><div class="result-line"><span>Наружный Ø</span><strong>${fmt(best.diameter,3)} мм</strong></div><div class="result-line"><span>Шаг</span><strong>${fmt(best.pitch,3)} мм${best.tpi?` · ${best.tpi} TPI`:''}</strong></div><div class="result-line"><span>Сверло, ориентировочно</span><strong>Ø${fmt(drill,2)} мм</strong></div><div class="result-line"><span>Угол профиля</span><strong>${best.angle}°</strong></div>${best.taper?`<div class="result-line"><span>Конусность</span><strong>${best.taper}</strong></div>`:''}</div><div class="action-row"><button class="secondary" data-save='${JSON.stringify({type:'Резьба',title:best.label,details:`${best.standard} · шаг ${fmt(best.pitch)} мм · сверло Ø${fmt(drill,2)} мм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></div></section><section class="panel glass"><h3>Другие совпадения</h3><div class="matches">${matches.slice(1).map(m=>`<div class="match"><div class="match-main"><strong>${m.label}</strong><span>${m.standard} · Ø${fmt(m.diameter)} · P ${fmt(m.pitch)}</span></div><span class="score">${Math.round(m.score)}%</span></div>`).join('')||'<span class="subtitle">Нет близких вариантов</span>'}</div></section>`;
}

function threadOptions(){return THREAD_DATA.filter(t=>t.standard==='ISO метрическая').map(t=>`<option value="${t.diameter}|${t.pitch}|${t.label}">${t.label}</option>`).join('')}
function drillView(){return `${header('drill','Подбор предварительного отверстия')}<section class="panel glass"><div class="field-grid"><div class="field full"><label>Метрическая резьба</label><select id="drillThread" class="select">${threadOptions()}</select></div><div class="field full"><label>Тип метчика</label><div class="segmented"><button data-drill-type="cut" class="${state.drillType==='cut'?'active':''}">Режущий</button><button data-drill-type="form" class="${state.drillType==='form'?'active':''}">Формующий</button></div></div><div class="field"><label>Заполнение профиля, %</label><input id="engagement" class="input" inputmode="decimal" value="75"></div><div class="field"><label>Материал</label><select id="material" class="select"><option>Сталь</option><option>Нержавеющая сталь</option><option>Алюминий</option><option>Латунь</option><option>Пластик</option></select></div></div><button id="drillBtn" class="primary" style="margin-top:14px">Рассчитать сверло</button></section><div id="drillResult"></div>`}
function drillCalc(){const [d,p,label]=$('#drillThread').value.split('|');const result=EngineeringCore.tapDrill(Number(d),Number(p),val('#engagement')||75,state.drillType),{hole,nearestTenth:nearest,engagement:e}=result;$('#drillResult').innerHTML=`<section class="result-card glass"><span class="result-label">Рекомендуемый диаметр</span><div class="result-big">Ø${fmt(nearest,1)} мм</div><div class="result-lines"><div class="result-line"><span>Резьба</span><strong>${label}</strong></div><div class="result-line"><span>Расчётный Ø</span><strong>${fmt(hole,3)} мм</strong></div><div class="result-line"><span>Тип метчика</span><strong>${state.drillType==='cut'?'Режущий':'Формующий'}</strong></div><div class="result-line"><span>Заполнение</span><strong>${fmt(e,0)}%</strong></div></div><p class="subtitle">Проверьте рекомендованный диаметр у производителя метчика, особенно для формующей резьбы и вязких материалов.</p><button class="secondary" data-save='${JSON.stringify({type:'Сверло под резьбу',title:`${label} → Ø${fmt(nearest,1)}`,details:`${state.drillType==='cut'?'Режущий':'Формующий'} метчик · ${e}%`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`}

function profileDiagram(p){return `<div class="technical-diagram"><svg viewBox="0 0 520 260" role="img" aria-label="Профиль метрической резьбы"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#36b7ff" stop-opacity=".82"/><stop offset="1" stop-color="#1c62b7" stop-opacity=".25"/></linearGradient></defs><path d="M40 215 150 50 260 215 370 50 480 215Z" fill="url(#fill)" stroke="#70ddff" stroke-width="4"/><path d="M150 35v-18m220 18v-18M150 24h220" stroke="#dcefff" stroke-width="2"/><path d="m150 24 12-6v12zm220 0-12-6v12z" fill="#dcefff"/><text x="260" y="17" fill="#fff" text-anchor="middle" font-size="19">P = ${fmt(p,3)} мм</text><path d="M195 94 A72 72 0 0 1 325 94" fill="none" stroke="#fff" stroke-width="2"/><text x="260" y="93" fill="#fff" text-anchor="middle" font-size="20">60°</text><path d="M25 50v165M18 50h18M18 215h18" stroke="#dcefff" stroke-width="2"/><text x="15" y="140" fill="#fff" text-anchor="middle" transform="rotate(-90 15 140)" font-size="16">H = ${fmt(.866025*p,3)} мм</text></svg></div>`}
function profileView(){return `${header('profile','Базовая геометрия ISO 60°')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Номинальный Ø, мм</label><input id="profileD" class="input" inputmode="decimal" value="10"></div><div class="field"><label>Шаг P, мм</label><input id="profileP" class="input" inputmode="decimal" value="1,5"></div></div><button id="profileBtn" class="primary" style="margin-top:14px">Построить профиль</button></section><div id="profileResult"></div>`}
function profileCalc(){const d=val('#profileD'),p=val('#profileP');if(!d||!p)return toast('Введите диаметр и шаг');const {H,d2,d3,D1,radialDepth}=EngineeringCore.metricProfile(d,p);$('#profileResult').innerHTML=`<section class="result-card glass"><span class="result-label">Метрический профиль</span><div class="result-big">M${fmt(d)} × ${fmt(p)}</div>${profileDiagram(p)}<div class="result-lines"><div class="result-line"><span>Теоретическая высота H</span><strong>${fmt(H,4)} мм</strong></div><div class="result-line"><span>Средний Ø d₂ / D₂</span><strong>${fmt(d2,4)} мм</strong></div><div class="result-line"><span>Наружная резьба, мин. Ø d₃</span><strong>${fmt(d3,4)} мм</strong></div><div class="result-line"><span>Внутренняя резьба, мин. Ø D₁</span><strong>${fmt(D1,4)} мм</strong></div><div class="result-line"><span>Радиальная глубина, наружная</span><strong>${fmt(radialDepth,4)} мм</strong></div></div><p class="subtitle">Это базовые размеры профиля без учёта поля допуска, скруглений вершины/впадины и рекомендаций изготовителя пластины.</p><button class="secondary" data-save='${JSON.stringify({type:'Профиль резьбы',title:`M${fmt(d)} × ${fmt(p)}`,details:`d₂ ${fmt(d2,4)} · d₃ ${fmt(d3,4)} · D₁ ${fmt(D1,4)} мм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`}

function favoritesView(){const items=favorites();return `${header('favorites','Хранится только на этом устройстве')}${items.length?`<section class="reference-list">${items.map((x,i)=>`<article class="ref-item glass"><small>${x.type}</small><strong>${x.title}</strong><p>${x.details}</p><div class="action-row"><button class="danger-btn" data-delete-favorite="${i}">Удалить</button></div></article>`).join('')}</section><button id="clearFavorites" class="danger-btn" style="margin-top:14px">Очистить избранное</button>`:`<section class="panel glass empty"><div class="empty-icon">☆</div><strong>Пока ничего не сохранено</strong><p>Добавляйте результаты расчётов и нужные строки справочника.</p></section>`}`}
function referenceView(){const groups=['Все',...new Set(FITS_DATA.map(x=>x.group))];const list=FITS_DATA.filter(x=>state.refGroup==='Все'||x.group===state.refGroup);return `${header('reference','Короткие подсказки для чтения чертежа')}<div class="tabs">${groups.map(g=>`<button class="tab ${g===state.refGroup?'active':''}" data-ref-group="${g}">${g}</button>`).join('')}</div><section class="reference-list">${list.map(x=>`<article class="ref-item glass"><small>${x.group}</small><strong>${x.code}</strong><p>${x.text}</p><button class="favorite-btn" data-save='${JSON.stringify({type:x.group,title:x.code,details:x.text}).replaceAll("'","&#39;")}' aria-label="Сохранить">☆</button></article>`).join('')}</section>`}

function geometryView(){return `${header('geometry','Три автономных калькулятора')}<div class="tabs"><button class="tab ${state.geometry==='cone'?'active':''}" data-geometry="cone">Конус</button><button class="tab ${state.geometry==='hex'?'active':''}" data-geometry="hex">Шестигранник</button><button class="tab ${state.geometry==='rotate'?'active':''}" data-geometry="rotate">Поворот координат</button></div>${state.geometry==='cone'?coneView():state.geometry==='hex'?hexView():rotateView()}`}
function coneView(){return `<section class="panel glass"><h2>Конус по двум диаметрам</h2><div class="field-grid"><div class="field"><label>Большой Ø D, мм</label><input id="coneD" class="input" value="60" inputmode="decimal"></div><div class="field"><label>Малый Ø d, мм</label><input id="coned" class="input" value="50" inputmode="decimal"></div><div class="field full"><label>Длина L, мм</label><input id="coneL" class="input" value="20" inputmode="decimal"></div></div><button id="coneBtn" class="primary" style="margin-top:14px">Рассчитать конус</button></section><div id="geometryResult"></div>`}
function coneCalc(){const D=val('#coneD'),d=val('#coned'),L=val('#coneL');if(!D||!d||!L||D<=d)return toast('Проверьте размеры конуса');const {half,full,ratio,radialDifference}=EngineeringCore.cone(D,d,L);$('#geometryResult').innerHTML=resultGeometry('Угол конуса',`${fmt(full,3)}°`,[['Угол на сторону',`${fmt(half,3)}°`],['Конусность',`1 : ${fmt(ratio,3)}`],['Перепад радиуса',`${fmt(radialDifference,3)} мм`]],`Конус Ø${fmt(D)}/Ø${fmt(d)} × ${fmt(L)}`)}
function hexView(){return `<section class="panel glass"><h2>Шестигранник</h2><div class="field"><label>Размер под ключ S, мм</label><input id="hexS" class="input" value="24" inputmode="decimal"></div><button id="hexBtn" class="primary" style="margin-top:14px">Рассчитать</button></section><div id="geometryResult"></div>`}
function hexCalc(){const s=val('#hexS');if(!s)return toast('Введите размер под ключ');const {acrossCorners:corners,side,area}=EngineeringCore.hex(s);$('#geometryResult').innerHTML=resultGeometry('Минимальный круг',`Ø${fmt(corners,3)} мм`,[['Сторона шестигранника',`${fmt(side,3)} мм`],['Площадь сечения',`${fmt(area,2)} мм²`],['Рекомендуемая заготовка',`не менее Ø${fmt(Math.ceil(corners),0)} мм`]],`Шестигранник S${fmt(s)}`)}
function rotateView(){return `<section class="panel glass"><h2>Поворот координат</h2><div class="field-grid"><div class="field"><label>X</label><input id="rotX" class="input" value="20" inputmode="decimal"></div><div class="field"><label>Y</label><input id="rotY" class="input" value="10" inputmode="decimal"></div><div class="field full"><label>Угол, ° против часовой</label><input id="rotA" class="input" value="30" inputmode="decimal"></div></div><button id="rotateBtn" class="primary" style="margin-top:14px">Повернуть точку</button></section><div id="geometryResult"></div>`}
function rotateCalc(){const x=val('#rotX'),y=val('#rotY'),a=val('#rotA')||0,{x:x2,y:y2,radius}=EngineeringCore.rotate(x,y,a);$('#geometryResult').innerHTML=resultGeometry('Новые координаты',`X ${fmt(x2,4)}`,[['Y',fmt(y2,4)],['Угол поворота',`${fmt(a,3)}°`],['Расстояние от нуля',fmt(radius,4)]],`Поворот (${fmt(x)}; ${fmt(y)}) на ${fmt(a)}°`)}
function resultGeometry(label,big,lines,title){const details=lines.map(x=>x.join(': ')).join(' · ');return `<section class="result-card glass"><span class="result-label">${label}</span><div class="result-big">${big}</div><div class="result-lines">${lines.map(([a,b])=>`<div class="result-line"><span>${a}</span><strong>${b}</strong></div>`).join('')}</div><button class="secondary" data-save='${JSON.stringify({type:'Геометрия',title,details}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`}

function toleranceDiagram(r){const zeroY=95,maxAbs=Math.max(1,Math.abs(r.lowerMicron),Math.abs(r.upperMicron)),scale=Math.min(4,55/maxAbs),y1=zeroY-r.upperMicron*scale,y2=zeroY-r.lowerMicron*scale,h=Math.max(4,y2-y1);return `<div class="technical-diagram"><svg viewBox="0 0 520 190" role="img" aria-label="Зона допуска ${r.field}"><path d="M55 ${zeroY}H485" stroke="#dcefff" stroke-width="2"/><text x="26" y="${zeroY+6}" fill="#fff" font-size="16">0</text><path d="M70 ${y1}H430V${y1+h}H70Z" fill="#259cff" fill-opacity=".3" stroke="#63d7ff" stroke-width="2"/><text x="446" y="${y1+h/2+6}" fill="#fff" font-size="19">${r.field}</text><text x="70" y="174" fill="#9fb9d3" font-size="15">${fmt(r.lowerMicron,1)} мкм</text><text x="350" y="174" fill="#9fb9d3" font-size="15">${fmt(r.upperMicron,1)} мкм</text></svg></div>`}
function fitsView(){return `${header('fits','Пределы размеров по ISO 286')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Номинальный размер, мм</label><input id="fitD" class="input" value="25,000" inputmode="decimal"></div><div class="field"><label>Поле допуска</label><select id="fitField" class="select"><optgroup label="Валы"><option>h6</option><option>h7</option><option>g6</option><option>f7</option><option>e8</option><option>d9</option><option>js6</option></optgroup><optgroup label="Отверстия"><option>H6</option><option>H7</option><option>H8</option><option>G7</option><option>F7</option><option>E8</option><option>D9</option><option>JS7</option></optgroup></select></div></div><button id="fitBtn" class="primary" style="margin-top:14px">Рассчитать</button></section><div id="fitResult"></div>`}
function fitsCalc(){try{const r=EngineeringCore.iso286(val('#fitD'),$('#fitField').value);$('#fitResult').innerHTML=`<section class="result-card glass"><span class="result-label">Целевой размер</span><div class="result-big">Ø${fmt(r.target,3)} мм</div><div class="result-lines"><div class="result-line"><span>Верхнее отклонение</span><strong>${r.upperMicron>=0?'+':''}${fmt(r.upperMicron/1000,3)} мм</strong></div><div class="result-line"><span>Нижнее отклонение</span><strong>${r.lowerMicron>=0?'+':''}${fmt(r.lowerMicron/1000,3)} мм</strong></div><div class="result-line"><span>Допустимый размер</span><strong>${fmt(r.min,3)}…${fmt(r.max,3)} мм</strong></div><div class="result-line"><span>Ширина допуска IT${r.grade}</span><strong>${fmt(r.toleranceMicron,0)} мкм</strong></div></div>${toleranceDiagram(r)}<button class="secondary" data-save='${JSON.stringify({type:'Допуск ISO 286',title:`Ø${fmt(r.nominal)} ${r.field}`,details:`${fmt(r.min,3)}…${fmt(r.max,3)} мм · цель ${fmt(r.target,4)} мм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function roughnessDiagram(){return `<div class="technical-diagram"><svg viewBox="0 0 520 225" role="img" aria-label="Шероховатость при точении"><path d="M30 164 Q85 85 140 164 Q195 85 250 164 Q305 85 360 164 Q415 85 490 164" fill="none" stroke="#63d7ff" stroke-width="4"/><path d="M140 182v25m110-25v25M140 198h110" stroke="#dcefff" stroke-width="2"/><text x="195" y="220" fill="#fff" font-size="18">f</text><path d="M245 72a55 55 0 0 1 72 57" fill="none" stroke="#fff" stroke-width="3"/><text x="320" y="80" fill="#fff" font-size="18">rε</text></svg></div>`}
function roughnessView(){return `${header('roughness','Теоретическая поверхность при точении')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Подача f, мм/об</label><input id="roughF" class="input" value="0,15" inputmode="decimal"></div><div class="field"><label>Радиус пластины rε, мм</label><input id="roughR" class="input" value="0,4" inputmode="decimal"></div><div class="field full"><label>Желаемая Ra, мкм</label><select id="roughTarget" class="select"><option value="0.8">0,8</option><option value="1.6" selected>1,6</option><option value="3.2">3,2</option><option value="6.3">6,3</option></select></div></div><button id="roughBtn" class="primary" style="margin-top:14px">Рассчитать Ra</button></section><div id="roughResult"></div>`}
function roughnessCalc(){try{const f=val('#roughF'),r=val('#roughR'),x=EngineeringCore.turningRoughness(f,r,Number($('#roughTarget').value)),range=x.ra<=.8?'Ra 0,4–0,8':x.ra<=1.6?'Ra 0,8–1,6':x.ra<=3.2?'Ra 1,6–3,2':x.ra<=6.3?'Ra 3,2–6,3':'грубее Ra 6,3';$('#roughResult').innerHTML=`<section class="result-card glass"><span class="result-label">Теоретический результат</span><div class="result-big">Ra ≈ ${fmt(x.ra,2)} мкм</div><div class="result-lines"><div class="result-line"><span>Расчётная Rz</span><strong>${fmt(x.rz,2)} мкм</strong></div><div class="result-line"><span>Ожидаемый диапазон</span><strong>${range}</strong></div><div class="result-line"><span>Подача для Ra ${fmt(x.targetRa,1)}</span><strong>≈ ${fmt(x.recommendedFeed,3)} мм/об</strong></div></div>${roughnessDiagram()}<p class="subtitle">Фактическая поверхность зависит от жёсткости, биения, геометрии пластины, материала и стружкообразования.</p><button class="secondary" data-save='${JSON.stringify({type:'Шероховатость',title:`Ra ≈ ${fmt(x.ra,2)} мкм`,details:`f ${fmt(f,3)} мм/об · rε ${fmt(r,2)} мм · Rz ${fmt(x.rz,2)} мкм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function positionView(){return `${header('position','Проверка координат отверстия или вала')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Номинальный X</label><input id="posBX" class="input" value="50" inputmode="decimal"></div><div class="field"><label>Номинальный Y</label><input id="posBY" class="input" value="30" inputmode="decimal"></div><div class="field"><label>Измеренный X</label><input id="posAX" class="input" value="50,03" inputmode="decimal"></div><div class="field"><label>Измеренный Y</label><input id="posAY" class="input" value="29,98" inputmode="decimal"></div><div class="field"><label>Допуск позиции Ø, мм</label><input id="posTol" class="input" value="0,10" inputmode="decimal"></div><div class="field"><label>Тип элемента</label><select id="posType" class="select"><option value="hole">Отверстие</option><option value="shaft">Вал</option></select></div><div class="field"><label>Фактический Ø</label><input id="posActual" class="input" value="10,05" inputmode="decimal"></div><div class="field"><label>Размер при MMC</label><input id="posMmc" class="input" value="10,00" inputmode="decimal"></div></div><button id="positionBtn" class="primary" style="margin-top:14px">Проверить позицию</button></section><div id="positionResult"></div>`}
function positionCalc(){const x=EngineeringCore.truePosition({basicX:val('#posBX'),basicY:val('#posBY'),actualX:val('#posAX'),actualY:val('#posAY'),tolerance:val('#posTol'),featureType:$('#posType').value,actualSize:val('#posActual'),mmcSize:val('#posMmc')});$('#positionResult').innerHTML=`<section class="result-card glass"><span class="result-label">${x.pass?'Размер проходит':'Размер не проходит'}</span><div class="result-big" style="color:${x.pass?'var(--ok)':'var(--danger)'}">Ø${fmt(x.position,3)} мм</div><div class="result-lines"><div class="result-line"><span>Отклонение X</span><strong>${x.dx>=0?'+':''}${fmt(x.dx,3)} мм</strong></div><div class="result-line"><span>Отклонение Y</span><strong>${x.dy>=0?'+':''}${fmt(x.dy,3)} мм</strong></div><div class="result-line"><span>Бонус MMC</span><strong>${fmt(x.bonus,3)} мм</strong></div><div class="result-line"><span>Доступный допуск</span><strong>Ø${fmt(x.allowed,3)} мм</strong></div></div><p class="subtitle">Проверка MMC применяется только когда это требование указано в рамке геометрического допуска на чертеже.</p><button class="secondary" data-save='${JSON.stringify({type:'Истинная позиция',title:`Ø${fmt(x.position,3)} мм · ${x.pass?'годно':'не годно'}`,details:`ΔX ${fmt(x.dx,3)} · ΔY ${fmt(x.dy,3)} · доступно Ø${fmt(x.allowed,3)} мм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}

function deflectionView(){return `${header('deflection','Оценка жёсткости расточной державки')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Диаметр державки, мм</label><input id="barD" class="input" value="25" inputmode="decimal"></div><div class="field"><label>Вылет L, мм</label><input id="barL" class="input" value="100" inputmode="decimal"></div><div class="field"><label>Глубина ap, мм</label><input id="barAp" class="input" value="1" inputmode="decimal"></div><div class="field"><label>Подача f, мм/об</label><input id="barF" class="input" value="0,15" inputmode="decimal"></div><div class="field full"><label>Обрабатываемый материал</label><select id="barKc" class="select"><option value="2400">AISI 304 · kc 2400 Н/мм²</option><option value="2100">Сталь C45 · kc 2100 Н/мм²</option><option value="1800">Сталь S235 · kc 1800 Н/мм²</option><option value="900">Латунь · kc 900 Н/мм²</option><option value="700">Алюминий · kc 700 Н/мм²</option><option value="300">Пластик · kc 300 Н/мм²</option></select></div></div><button id="deflectionBtn" class="primary" style="margin-top:14px">Оценить прогиб</button></section><div id="deflectionResult"></div>`}
function deflectionCalc(){try{const x=EngineeringCore.boringBarDeflection({diameter:val('#barD'),overhang:val('#barL'),depth:val('#barAp'),feed:val('#barF'),kc:Number($('#barKc').value)}),risk=x.level==='Хорошая жёсткость'?'var(--ok)':x.level==='Допустимо'?'#ffc857':'var(--danger)';$('#deflectionResult').innerHTML=`<section class="result-card glass"><span class="result-label">Расчётный прогиб</span><div class="result-big">${fmt(x.deflection,3)} мм</div><div class="result-lines"><div class="result-line"><span>Отношение вылета L/D</span><strong>${fmt(x.ratio,2)}</strong></div><div class="result-line"><span>Сила резания Fc</span><strong>≈ ${fmt(x.cuttingForce,0)} Н</strong></div><div class="result-line"><span>Расчётная радиальная сила</span><strong>≈ ${fmt(x.radialForce,0)} Н</strong></div><div class="result-line"><span>Оценка</span><strong style="color:${risk}">${x.level}</strong></div></div><p class="subtitle">Инженерная оценка консольной стальной державки. Реальный прогиб зависит от закрепления, геометрии пластины, износа и прерывистого резания.</p><button class="secondary" data-save='${JSON.stringify({type:'Прогиб державки',title:`${fmt(x.deflection,3)} мм · L/D ${fmt(x.ratio,2)}`,details:`Fc ${fmt(x.cuttingForce,0)} Н · ${x.level}`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function materialOptions(){return MATERIAL_DENSITIES.map((m,i)=>`<option value="${m.density}" ${i===0?'selected':''}>${m.name} · ${fmt(m.density,2)} г/см³</option>`).join('')}
function weightFields(){if(state.weightShape==='tube')return `<div class="field"><label>Наружный Ø, мм</label><input id="stockD" class="input" value="50" inputmode="decimal"></div><div class="field"><label>Внутренний Ø, мм</label><input id="stockInner" class="input" value="30" inputmode="decimal"></div><div class="field full"><label>Длина, мм</label><input id="stockL" class="input" value="120" inputmode="decimal"></div>`;if(state.weightShape==='hex')return `<div class="field"><label>Размер под ключ S, мм</label><input id="stockS" class="input" value="36" inputmode="decimal"></div><div class="field"><label>Длина, мм</label><input id="stockL" class="input" value="120" inputmode="decimal"></div>`;if(state.weightShape==='rect')return `<div class="field"><label>Ширина, мм</label><input id="stockW" class="input" value="50" inputmode="decimal"></div><div class="field"><label>Высота, мм</label><input id="stockH" class="input" value="20" inputmode="decimal"></div><div class="field full"><label>Длина, мм</label><input id="stockL" class="input" value="120" inputmode="decimal"></div>`;if(state.weightShape==='sphere')return `<div class="field full"><label>Диаметр шара, мм</label><input id="stockD" class="input" value="50" inputmode="decimal"></div>`;return `<div class="field"><label>Диаметр, мм</label><input id="stockD" class="input" value="50" inputmode="decimal"></div><div class="field"><label>Длина, мм</label><input id="stockL" class="input" value="120" inputmode="decimal"></div>`}
function weightView(){return `${header('weight','Масса одной заготовки и партии')}<section class="panel glass"><div class="field-grid"><div class="field full"><label>Форма</label><select id="stockShape" class="select"><option value="round" ${state.weightShape==='round'?'selected':''}>Круг</option><option value="tube" ${state.weightShape==='tube'?'selected':''}>Труба</option><option value="hex" ${state.weightShape==='hex'?'selected':''}>Шестигранник</option><option value="rect" ${state.weightShape==='rect'?'selected':''}>Прямоугольник</option><option value="sphere" ${state.weightShape==='sphere'?'selected':''}>Шар</option></select></div><div class="field full"><label>Материал</label><select id="stockMaterial" class="select">${materialOptions()}</select></div>${weightFields()}<div class="field full"><label>Количество, шт.</label><input id="stockQty" class="input" value="10" inputmode="numeric"></div></div><button id="weightBtn" class="primary" style="margin-top:14px">Рассчитать вес</button></section><div id="weightResult"></div>`}
function stockDrawing(shape){if(shape==='hex')return `<svg viewBox="0 0 520 230"><path d="M100 55h240l70 55-70 65H100l-55-60z" fill="rgba(47,151,232,.18)" stroke="currentColor" stroke-width="3"/><path d="M100 55 45 115m295-60 70 55m-70 65 70-65" fill="none" stroke="currentColor" stroke-width="2"/><path d="M70 195h300m-300-8v16m300-16v16" stroke="#fff"/><text x="220" y="220" fill="#fff" text-anchor="middle">L</text></svg>`;if(shape==='rect')return `<svg viewBox="0 0 520 230"><path d="M75 70h280l90 45v70H165l-90-45z" fill="rgba(47,151,232,.18)" stroke="currentColor" stroke-width="3"/><path d="m75 70 90 45h280M165 115v70" fill="none" stroke="currentColor"/><text x="255" y="210" fill="#fff" text-anchor="middle">L × W × H</text></svg>`;if(shape==='sphere')return `<svg viewBox="0 0 520 230"><circle cx="260" cy="112" r="84" fill="rgba(47,151,232,.18)" stroke="currentColor" stroke-width="3"/><ellipse cx="260" cy="112" rx="84" ry="30" fill="none" stroke="currentColor"/><path d="M176 112h168" stroke="#fff"/><text x="260" y="104" fill="#fff" text-anchor="middle">ØD</text></svg>`;return `<svg viewBox="0 0 520 230"><defs><linearGradient id="bar" x1="0" x2="1"><stop stop-color="#163b60"/><stop offset=".5" stop-color="#3c769f"/><stop offset="1" stop-color="#0b243d"/></linearGradient></defs><path d="M105 45h290c38 0 60 31 60 69s-22 69-60 69H105z" fill="url(#bar)" stroke="currentColor" stroke-width="3"/><ellipse cx="105" cy="114" rx="42" ry="69" fill="#102d49" stroke="currentColor" stroke-width="3"/>${shape==='tube'?'<ellipse cx="105" cy="114" rx="22" ry="40" fill="#03101f" stroke="currentColor" stroke-width="3"/>':''}<path d="M105 202h290m-290-9v18m290-18v18" stroke="#fff"/><text x="250" y="225" fill="#fff" text-anchor="middle">L</text><path d="M47 45v138m-8-138h16m-16 138h16" stroke="#fff"/><text x="28" y="120" fill="#fff" transform="rotate(-90 28 120)" text-anchor="middle">ØD</text></svg>`}
function weightCalc(){try{const params={shape:state.weightShape,density:Number($('#stockMaterial').value),quantity:Math.max(1,Math.round(val('#stockQty'))),diameter:val('#stockD'),innerDiameter:val('#stockInner'),length:val('#stockL'),width:val('#stockW'),height:val('#stockH'),acrossFlats:val('#stockS')},r=EngineeringCore.stockWeight(params),material=$('#stockMaterial').selectedOptions[0].text.split(' · ')[0];$('#weightResult').innerHTML=`<section class="result-card glass"><span class="result-label">Масса заготовки</span><div class="result-big">${fmt(r.mass,3)} кг</div><div class="result-lines"><div class="result-line"><span>Объём</span><strong>${fmt(r.volumeCm3,2)} см³</strong></div><div class="result-line"><span>Плотность</span><strong>${fmt(params.density,2)} г/см³</strong></div><div class="result-line"><span>Масса ${r.quantity} шт.</span><strong>${fmt(r.totalMass,2)} кг</strong></div></div><div class="blueprint">${stockDrawing(state.weightShape)}</div><button class="secondary" data-save='${JSON.stringify({type:'Вес заготовки',title:`${fmt(r.mass,3)} кг · ${material}`,details:`${r.quantity} шт. = ${fmt(r.totalMass,2)} кг`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function boltView(){return `${header('bolt','Координаты равномерно расположенных отверстий')}<section class="panel glass"><div class="field-grid"><div class="field full"><label>Диаметр окружности PCD, мм</label><input id="boltPcd" class="input" value="120" inputmode="decimal"></div><div class="field"><label>Количество отверстий</label><input id="boltCount" class="input" value="8" inputmode="numeric"></div><div class="field"><label>Начальный угол, °</label><input id="boltStart" class="input" value="0" inputmode="decimal"></div></div><button id="boltBtn" class="primary" style="margin-top:14px">Рассчитать координаты</button></section><div id="boltResult"></div>`}
function boltDiagram(r){const pts=r.points.map(p=>{const a=p.angle*Math.PI/180,x=160+112*Math.cos(a),y=160-112*Math.sin(a);return `<circle cx="${x}" cy="${y}" r="8" fill="#06101d" stroke="currentColor" stroke-width="3"/><text x="${x}" y="${y-13}" fill="#fff" text-anchor="middle" font-size="11">${p.number}</text>`}).join('');return `<svg viewBox="0 0 320 320"><circle cx="160" cy="160" r="112" fill="none" stroke="currentColor" stroke-width="3"/><path d="M30 160h260M160 30v260" stroke="currentColor" opacity=".3" stroke-dasharray="6 6"/><circle cx="160" cy="160" r="4" fill="currentColor"/>${pts}<text x="160" y="154" fill="#fff" text-anchor="middle" font-size="15">PCD Ø${fmt(r.pcd,2)}</text></svg>`}
function boltCalc(){try{const r=EngineeringCore.boltCircle(val('#boltPcd'),Math.round(val('#boltCount')),val('#boltStart')||0);state.lastBolt=r;$('#boltResult').innerHTML=`<section class="result-card glass"><span class="result-label">Координаты отверстий</span><div class="blueprint">${boltDiagram(r)}</div><div style="overflow:auto"><table class="coordinate-table"><thead><tr><th>№</th><th>Угол</th><th>X</th><th>Y</th></tr></thead><tbody>${r.points.map(p=>`<tr><td>${p.number}</td><td>${fmt(p.angle,3)}°</td><td>${fmt(p.x,3)}</td><td>${fmt(p.y,3)}</td></tr>`).join('')}</tbody></table></div><button id="copyBolt" class="secondary">Копировать таблицу</button></section>`;$('#copyBolt').onclick=copyBolt}catch(e){toast(e.message)}}
async function copyBolt(){const r=state.lastBolt;if(!r)return;const text=['№\tУгол\tX\tY',...r.points.map(p=>`${p.number}\t${fmt(p.angle,3)}°\t${fmt(p.x,3)}\t${fmt(p.y,3)}`)].join('\n');try{await navigator.clipboard.writeText(text);toast('Таблица скопирована')}catch{toast('Не удалось скопировать')}}

function wiresView(){return `${header('wires','Теоретическое измерение наружной резьбы 60°')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Номинальный Ø, мм</label><input id="wireD" class="input" value="10" inputmode="decimal"></div><div class="field"><label>Шаг P, мм</label><input id="wireP" class="input" value="1,5" inputmode="decimal"></div><div class="field full"><label>Диаметр проволочки, мм</label><input id="wireW" class="input" placeholder="Пусто = оптимальная" inputmode="decimal"><span class="input-hint">Оптимальная проволочка рассчитывается автоматически.</span></div></div><button id="wireBtn" class="primary" style="margin-top:14px">Рассчитать измерение</button></section><div id="wireResult"></div>`}
function wiresDrawing(r){return `<svg viewBox="0 0 520 260"><path d="M35 215 125 55l90 160 90-160 90 160 90-160" fill="none" stroke="currentColor" stroke-width="4"/>${[[137,145],[293,145],[215,210]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="28" fill="#102f4e" stroke="#70dcff" stroke-width="3"/>`).join('')}<path d="M110 28h210m-210-9v18m210-18v18" stroke="#fff"/><text x="215" y="20" fill="#fff" text-anchor="middle">M = ${fmt(r.measurement,4)} мм</text><text x="138" y="151" fill="#fff" text-anchor="middle" font-size="13">w</text></svg>`}
function wiresCalc(){try{const r=EngineeringCore.threeWire(val('#wireD'),val('#wireP'),val('#wireW'));$('#wireResult').innerHTML=`<section class="result-card glass"><span class="result-label">Размер по трём проволочкам</span><div class="result-big">M ${fmt(r.measurement,4)} мм</div><div class="result-lines"><div class="result-line"><span>Средний диаметр d₂</span><strong>${fmt(r.pitchDiameter,4)} мм</strong></div><div class="result-line"><span>Оптимальная проволочка</span><strong>Ø${fmt(r.bestWire,4)} мм</strong></div><div class="result-line"><span>Использованная проволочка</span><strong>Ø${fmt(r.wire,4)} мм</strong></div></div><div class="blueprint">${wiresDrawing(r)}</div><p class="subtitle">Теоретический базовый размер без поля допуска и поправок на фактический диаметр проволочек.</p><button class="secondary" data-save='${JSON.stringify({type:'Резьба по 3 проволочкам',title:`M${fmt(r.metricDiameter)} × ${fmt(r.pitch)}`,details:`M ${fmt(r.measurement,4)} мм · проволочка Ø${fmt(r.wire,4)}`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function drillPointView(){return `${header('drillpoint','Геометрия вершины спирального сверла')}<section class="panel glass"><div class="field-grid"><div class="field"><label>Диаметр сверла, мм</label><input id="pointD" class="input" value="10" inputmode="decimal"></div><div class="field"><label>Угол при вершине, °</label><select id="pointA" class="select"><option>90</option><option selected>118</option><option>130</option><option>135</option><option>140</option></select></div><div class="field full"><label>Требуемая цилиндрическая глубина, мм</label><input id="pointDepth" class="input" value="20" inputmode="decimal"></div></div><button id="pointBtn" class="primary" style="margin-top:14px">Рассчитать глубину</button></section><div id="pointResult"></div>`}
function pointDrawing(r){return `<svg viewBox="0 0 520 245"><path d="M150 25h220v105l-110 85-110-85z" fill="rgba(47,151,232,.18)" stroke="currentColor" stroke-width="3"/><path d="M260 25v190M150 130h220" stroke="currentColor" opacity=".35" stroke-dasharray="6 5"/><path d="M395 130v85m-8-85h16m-16 85h16" stroke="#fff"/><text x="420" y="178" fill="#fff">h = ${fmt(r.length,3)}</text><path d="M220 183a55 55 0 0 1 80 0" fill="none" stroke="#fff"/><text x="260" y="178" fill="#fff" text-anchor="middle">${fmt(r.pointAngle,0)}°</text></svg>`}
function pointCalc(){try{const depth=val('#pointDepth'),r=EngineeringCore.drillPointLength(val('#pointD'),val('#pointA')),full=depth+r.length;$('#pointResult').innerHTML=`<section class="result-card glass"><span class="result-label">Длина вершины</span><div class="result-big">${fmt(r.length,3)} мм</div><div class="result-lines"><div class="result-line"><span>Угол при вершине</span><strong>${fmt(r.pointAngle,0)}°</strong></div><div class="result-line"><span>Цилиндрическая глубина</span><strong>${fmt(depth,3)} мм</strong></div><div class="result-line"><span>Полная глубина сверления</span><strong>${fmt(full,3)} мм</strong></div></div><div class="blueprint">${pointDrawing(r)}</div><button class="secondary" data-save='${JSON.stringify({type:'Вершина сверла',title:`Ø${fmt(r.diameter)} · ${fmt(r.pointAngle,0)}°`,details:`вершина ${fmt(r.length,3)} мм · полная глубина ${fmt(full,3)} мм`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function timeFields(){if(state.timeType==='drill')return `<div class="field"><label>Глубина, мм</label><input id="timeL" class="input" value="30" inputmode="decimal"></div><div class="field"><label>Добавка вершины, мм</label><input id="timeApproach" class="input" value="3" inputmode="decimal"></div><div class="field full"><label>Коэффициент циклов/отводов</label><input id="timePeck" class="input" value="1,15" inputmode="decimal"></div>`;if(state.timeType==='cutoff')return `<div class="field"><label>Диаметр детали, мм</label><input id="timeDiameter" class="input" value="50" inputmode="decimal"></div><div class="field"><label>Подход, мм</label><input id="timeApproach" class="input" value="2" inputmode="decimal"></div>`;return `<div class="field"><label>Длина прохода, мм</label><input id="timeL" class="input" value="100" inputmode="decimal"></div><div class="field"><label>Подход, мм</label><input id="timeApproach" class="input" value="3" inputmode="decimal"></div><div class="field"><label>Начальный Ø, мм</label><input id="timeStartD" class="input" value="52" inputmode="decimal"></div><div class="field"><label>Конечный Ø, мм</label><input id="timeEndD" class="input" value="46" inputmode="decimal"></div><div class="field full"><label>Глубина за проход ap, мм</label><input id="timeAp" class="input" value="1,5" inputmode="decimal"></div>`}
function timeView(){return `${header('time','Основное машинное время')}<div class="tabs"><button class="tab ${state.timeType==='turn'?'active':''}" data-time-type="turn">Точение</button><button class="tab ${state.timeType==='drill'?'active':''}" data-time-type="drill">Сверление</button><button class="tab ${state.timeType==='cutoff'?'active':''}" data-time-type="cutoff">Отрезка</button></div><section class="panel glass"><div class="field-grid"><div class="field"><label>Обороты S, об/мин</label><input id="timeRpm" class="input" value="800" inputmode="decimal"></div><div class="field"><label>Подача f, мм/об</label><input id="timeFeed" class="input" value="0,15" inputmode="decimal"></div>${timeFields()}</div><button id="timeBtn" class="primary" style="margin-top:14px">Рассчитать время</button></section><div id="timeResult"></div>`}
function timeCalc(){try{const r=EngineeringCore.machiningTime({type:state.timeType,rpm:val('#timeRpm'),feed:val('#timeFeed'),length:val('#timeL'),approach:val('#timeApproach'),diameter:val('#timeDiameter'),startDiameter:val('#timeStartD'),endDiameter:val('#timeEndD'),depthPerPass:val('#timeAp'),peckFactor:val('#timePeck')||1});$('#timeResult').innerHTML=`<section class="result-card glass"><span class="result-label">Основное время</span><div class="result-big">${r.seconds<60?`${fmt(r.seconds,1)} с`:`${fmt(r.minutes,2)} мин`}</div><div class="result-lines"><div class="result-line"><span>Подача в минуту</span><strong>${fmt(r.feedRate,2)} мм/мин</strong></div><div class="result-line"><span>Расчётный путь</span><strong>${fmt(r.travel,2)} мм</strong></div><div class="result-line"><span>Количество проходов</span><strong>${r.passes}</strong></div><div class="result-line"><span>Время в секундах</span><strong>${fmt(r.seconds,2)} с</strong></div></div><p class="subtitle">Основное время без смены инструмента, разгона, измерений и вспомогательных перемещений.</p><button class="secondary" data-save='${JSON.stringify({type:'Время обработки',title:`${fmt(r.seconds,1)} с`,details:`${state.timeType} · ${r.passes} проход(а) · ${fmt(r.feedRate,2)} мм/мин`}).replaceAll("'","&#39;")}'>☆ Сохранить</button></section>`;bindSaves()}catch(e){toast(e.message)}}

function wearIcon(id){const marks={flank:'<path d="m8 26 6-20 13 5-6 17z"/><path d="m12 22 11 3"/>',crater:'<path d="m6 25 7-19 14 6-7 16z"/><ellipse cx="18" cy="15" rx="5" ry="3"/>',notch:'<path d="m6 25 7-19 14 6-7 16z"/><path d="m11 21 5-4-2-5"/>',chipping:'<path d="m6 25 7-19 14 6-7 16z"/><path d="m10 22 4-4 3 3 4-5"/>',deformation:'<path d="m6 25 7-19 14 6-7 16z"/><path d="m10 23 8-1 5-6"/>',bue:'<path d="m6 25 7-19 14 6-7 16z"/><path d="m12 10 5 1 2 5-5 2-4-3z"/>',thermal:'<path d="m6 25 7-19 14 6-7 16z"/><path d="m12 11 9 12m-5-10 7 9m-10-5 5 7"/>'};return `<svg viewBox="0 0 32 32">${marks[id]}</svg>`}
function wearView(){const item=WEAR_DATA.find(x=>x.id===state.wear);return `${header('wear','Визуальная диагностика без интернета')}<section class="wear-grid">${WEAR_DATA.map(x=>`<button class="wear-card ${x.id===state.wear?'active':''}" data-wear="${x.id}">${wearIcon(x.id)}<strong>${x.title}</strong></button>`).join('')}</section><section class="result-card glass"><span class="result-label">Выбранный вид износа</span><div class="result-big" style="font-size:25px;letter-spacing:-.02em">${item.title}</div><div class="blueprint">${wearIcon(item.id).replace('<svg','<svg style="max-height:180px"')}</div><h3>Как выглядит</h3><p class="subtitle">${item.sign}</p><h3>Вероятные причины</h3><ul class="advice-list">${item.causes.map(x=>`<li>${x}</li>`).join('')}</ul><h3 style="margin-top:18px">Что сделать</h3><ul class="advice-list">${item.actions.map(x=>`<li>${x}</li>`).join('')}</ul></section>`}

function settingsView(){const light=document.body.classList.contains('light');return `${header('settings','Внешний вид и установка')}<section class="panel glass settings-list"><div class="setting-row"><div><strong>Светлая тема</strong><small>Переключается вручную</small></div><button id="themeSwitch" class="switch ${light?'on':''}" aria-label="Переключить тему"></button></div><div class="setting-row"><div><strong>Версия</strong><small>3.0.0 · автономная PWA</small></div></div><div><strong>Установка на iPhone</strong><p class="install-note">Откройте приложение в Safari → нажмите «Поделиться» → «На экран Домой». После первого полного запуска оно будет доступно без интернета.</p></div></section>`}

function render(){app.innerHTML=state.route==='home'?home():state.route==='identify'?identifyView():state.route==='drill'?drillView():state.route==='profile'?profileView():state.route==='favorites'?favoritesView():state.route==='reference'?referenceView():state.route==='geometry'?geometryView():state.route==='fits'?fitsView():state.route==='roughness'?roughnessView():state.route==='position'?positionView():state.route==='deflection'?deflectionView():state.route==='weight'?weightView():state.route==='bolt'?boltView():state.route==='wires'?wiresView():state.route==='drillpoint'?drillPointView():state.route==='time'?timeView():state.route==='wear'?wearView():settingsView();bind()}
function bindSaves(){
  if(document.body.dataset.projectSaveBound)return;
  document.body.dataset.projectSaveBound='true';
  document.addEventListener('click',event=>{
    const b=event.target.closest('[data-save]');if(!b)return;
    const item={...JSON.parse(b.dataset.save),savedAt:new Date().toISOString()},items=favorites();
    if(items.some(x=>x.type===item.type&&x.title===item.title))return toast('Уже сохранено в Проектах');
    items.unshift(item);saveFavorites(items.slice(0,100));b.textContent='✓ В Проектах';toast('Результат сохранён в Проекты');
  });
}
function bind(){
  $$('[data-tool]').forEach(b=>b.onclick=()=>setRoute(b.dataset.tool));$('[data-back]')?.addEventListener('click',()=>setRoute('home'));
  $$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'}));
  $$('[data-pitch-mode]').forEach(b=>b.onclick=()=>{state.pitchMode=b.dataset.pitchMode;render()});
  $$('[data-drill-type]').forEach(b=>b.onclick=()=>{state.drillType=b.dataset.drillType;render()});
  $$('[data-ref-group]').forEach(b=>b.onclick=()=>{state.refGroup=b.dataset.refGroup;render()});
  $$('[data-geometry]').forEach(b=>b.onclick=()=>{state.geometry=b.dataset.geometry;render()});
  $$('[data-time-type]').forEach(b=>b.onclick=()=>{state.timeType=b.dataset.timeType;render()});
  $$('[data-wear]').forEach(b=>b.onclick=()=>{state.wear=b.dataset.wear;render()});
  $('#stockShape')?.addEventListener('change',e=>{state.weightShape=e.target.value;render()});
  $('#identifyBtn')?.addEventListener('click',identifyCalc);$('#drillBtn')?.addEventListener('click',drillCalc);$('#profileBtn')?.addEventListener('click',profileCalc);$('#coneBtn')?.addEventListener('click',coneCalc);$('#hexBtn')?.addEventListener('click',hexCalc);$('#rotateBtn')?.addEventListener('click',rotateCalc);$('#fitBtn')?.addEventListener('click',fitsCalc);$('#roughBtn')?.addEventListener('click',roughnessCalc);$('#positionBtn')?.addEventListener('click',positionCalc);$('#deflectionBtn')?.addEventListener('click',deflectionCalc);$('#weightBtn')?.addEventListener('click',weightCalc);$('#boltBtn')?.addEventListener('click',boltCalc);$('#wireBtn')?.addEventListener('click',wiresCalc);$('#pointBtn')?.addEventListener('click',pointCalc);$('#timeBtn')?.addEventListener('click',timeCalc);
  bindSaves();
  $$('[data-delete-favorite]').forEach(b=>b.onclick=()=>{const items=favorites();items.splice(Number(b.dataset.deleteFavorite),1);saveFavorites(items);render()});
  $('#clearFavorites')?.addEventListener('click',()=>{saveFavorites([]);render();toast('Избранное очищено')});
  $('#themeSwitch')?.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('engineeringTheme',document.body.classList.contains('light')?'light':'dark');render()});
  $$('.input').forEach(input=>input.addEventListener('focus',()=>input.select()));
}

$$('.dock-btn').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));
if(localStorage.getItem('engineeringTheme')==='light')document.body.classList.add('light');
const updateOnline=()=>$('#offlineBadge').hidden=navigator.onLine;addEventListener('online',updateOnline);addEventListener('offline',updateOnline);updateOnline();
render();
const reportHeight=()=>parent.postMessage({type:'cnc-calculations-height',height:document.documentElement.scrollHeight},location.origin);
new ResizeObserver(reportHeight).observe(document.body);addEventListener('load',reportHeight);
